description: PhillyTools ConfigFile for s3prl

# AML 
target:
#  name: itpeastusv100cl
#  name: itpeusp100cl
#  name: itpseasiav100cl
#  name: itpscusv100cl
  name: itpeusp40cl
  service: amlk8s
  vc: resrchvc
#  vc: speech-itp-default


# docker environment
environment:
  image: sanyuanchen/s3prl_v2:latest

# code dir
code:
  local_dir: .

# job configuration
  # amlt run .\scripts\itp\pretrained_models_ic.yaml pretrained_models_ic_WavLM-Large-More_lr1e4 -y
jobs:
  - name: training
    sku: G1
    sku_count: 1
    command:
      - bash scripts/itp/bash/pretrained_models_ic.sh hubert_models WavLM-Large-More  128 1e-3 1 0 _sanych_spk_hubert_large
      - bash scripts/itp/bash/pretrained_models_ic.sh hubert_models WavLM-Large-More  128 1e-4 1 0 _sanych_spk_hubert_large
#      - bash scripts/itp/bash/pretrained_models_ic.sh hubert_models WavLM-Large-More  128 2e-4 1 0 _sanych_spk_hubert_large
#      - bash scripts/itp/bash/pretrained_models_ic.sh hubert_models WavLM-Large-More  128 5e-4 1 0 _sanych_spk_hubert_large
#      - bash scripts/itp/bash/pretrained_models_ic.sh hubert_models WavLM-Large  128 5e-4 1 0 _sanych_spk_hubert_large
#      - bash scripts/itp/bash/pretrained_models_ic.sh hubert_models WavLM-Base-Plus  128 2e-5 1 0 _sanych_spk_hubert_large
#      - bash scripts/itp/bash/pretrained_models_ic.sh hubert_models WavLM-Base  128 5e-5 1 0 _sanych_spk_hubert_large
#      - bash scripts/itp/bash/pretrained_models_ic.sh hubert_models WavLM-Base  128 5e-4 1 0 _sanych_spk_hubert_large
#      - bash scripts/itp/bash/pretrained_models_ic.sh hubert_models UniSpeech-SAT-Base-plus  128 1e-4 1 0 _sanych_spk_hubert_large
      - sleep infinity

# azure blob configuration
storage:
  data_blob:
    container_name: models
    mount_dir: /datablob
    storage_account_name: tsstd01eus
#    storage_account_name: tsstd01scus
#    storage_account_name: tsstd01wus2
    mount_options:
      - -o
      - attr_timeout=240
      - -o
      - entry_timeout=240
      - -o
      - negative_timeout=120
      - -o
      - allow_other
      - --log-level=LOG_WARNING
      - --file-cache-timeout-in-seconds=3600