description: PhillyTools ConfigFile for s3prl

# AML 
target:
#  name: itpeastusv100cl
#  name: itp-v100-scus-2
#  name: itpeusp100cl
  name: itpeusp40cl
  service: amlk8s
#  vc: speech-itp-ahuna
#  vc: speech-itp-am-e2e
  vc: resrchvc
#  queue: bonus

# docker environment
environment:
  image: sanyuanchen/s3prl_v2:s3prl_v2

# code dir
code:
  local_dir: .

# job configuration
  # amlt run .\scripts\itp\pretrained_models_er.yaml pretrained_models_er_phf_char_zhuoyuan_b32_1e4_1_f1 -y

jobs:
  - name: training
    sku: G4
#    sku: G1
    sku_count: 1
    command:
      # recommended hyperparamters: bs 32, lr 1e-4,  acc 1, node 4

      # wavlm base+
      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models phf_char_zhuoyuan 32 1e-4 1 4 5
#      - bash scripts/itp/bash/pretrained_models_er.sh model/data2vec da_data2vec_960h 32 1e-4 1 4 5
#      - bash scripts/itp/bash/pretrained_models_er.sh model/data2vec mix_data2vec_94k 32 1e-4 1 4 5
#      - bash scripts/itp/bash/pretrained_models_er.sh model/data2vec data2vec_960h_devclean_ziyang 32 1e-4 1 4 5
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mn_hubert_pretrain_small_iter3_94k_mnp05_mp02_grep_mt2800k_step600k 32 1e-4 1 4 5
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models hubert_base_relative_hybrid100h_ali 32 1e-4 1 4 5
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mnb_hubert_pretrain_base_iter3_94k_mnp05_mp02_msp0_msrp0_grep 32 1e-4 1 4 5
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mnb_hubert_pretrain_base_iter3_94k_mnp05_mp02_msp0_msrp0_grep 32 5e-5 1 4 3
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mnb_hubert_pretrain_base_iter3_94k_mnp0_mp02_msp05_msrp05_grep 32 1e-4 1 4 5
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mnb_hubert_pretrain_base_iter3_94k_mnp0_mp02_msp05_msrp05_grep 32 5e-5 1 4 5
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mn_hubert_pretrain_base_iter3_94k_mnp05_mp02_grep 32 5e-5 1 4 5
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mn_hubert_pretrain_base_iter3_94k_mnp05_mp02_grep 32 1e-4 1 4 5
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mnb_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep 32 5e-5 1 4 5
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mnb_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep 32 1e-4 1 4 5
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mn_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep_1200kstep_1025k 32 1e-4 1 4 1
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mn_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep_1200kstep_1025k 32 1e-4 1 4 2
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mn_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep_1200kstep_1025k 32 1e-4 1 4 3
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mn_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep_1200kstep_1025k 32 1e-4 1 4 4
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mn_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep_1200kstep_1025k 32 1e-4 1 4 5

      # wavlm large
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mn_hubert_pretrain_large_94k_mnp01_mp02_grep_700k_475kstep_conti_700k_attrelax 32 1e-5 1 4 5
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mn_hubert_pretrain_large_94k_mnp0_mp02_grep_700k_600kstep_conti_attrelax 32 1e-5 1 4 5
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mn_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep_1200kstep_1025k 32 1e-5 1 4 1
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mn_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep_1200kstep_1025k 32 1e-5 1 4 2
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mn_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep_1200kstep_1025k 32 1e-5 1 4 3
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mn_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep_1200kstep_1025k 32 1e-5 1 4 4
#      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mn_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep_1200kstep_1025k 32 1e-5 1 4 5

# azure blob configuration
storage:
  data_blob:
    container_name: models
    mount_dir: /datablob
#    storage_account_name: tsstd01eus
    storage_account_name: tsstd01scus
#    storage_account_name: tsstd01wus2
    mount_options:
      - -o
      - attr_timeout=240
      - -o
      - entry_timeout=240
      - -o
      - negative_timeout=120
      - -o
      - allow_other
      - --log-level=LOG_WARNING
      - --file-cache-timeout-in-seconds=3600