description: PhillyTools ConfigFile for s3prl

# AML 
target:
#  name: itpeastusv100cl
#  name: itpeusp100cl
#  name: itpscusv100cl
#  name: itp-v100-scus-2
  name: itp-v100-wus2
#  name: itpeusp40cl
#  name: itp-p40-eus-01
  service: amlk8s
#  vc: resrchvc
#  vc: speech-itp-ahuna
  vc: speech-itp-am-e2e
#  vc: speech-itp-default
  queue: bonus

# docker environment
environment:
  image: sanyuanchen/s3prl_v2:s3prl_v2

# code dir
code:
  local_dir: .

# job configuration
  # amlt run .\scripts\itp\pretrained_models_pr.yaml pretrained_models_pr_mn_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep_1200kstep_1025k_lr5e4 -y
jobs:
  - name: training
    sku: G8
    sku_count: 1
    command:
      # recommended hyperparamters: bs 128, lr 1e-4,  acc 2, node 4 or 8

      # wavlm base+
      - bash scripts/itp/bash/pretrained_models_pr.sh hubert_models mn_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep_1200kstep_1025k  128 5e-4 2 8

      # wavlm large
#      - bash scripts/itp/bash/pretrained_models_pr.sh hubert_models mn_hubert_pretrain_large_94k_mnp0_mp02_grep_700k_600kstep_conti_620  128 2e-4 2 8

# azure blob configuration
storage:
  data_blob:
    container_name: models
    mount_dir: /datablob
#    storage_account_name: tsstd01eus
#    storage_account_name: tsstd01scus
    storage_account_name: tsstd01wus2
    mount_options:
      - -o
      - attr_timeout=240
      - -o
      - entry_timeout=240
      - -o
      - negative_timeout=120
      - -o
      - allow_other
      - --log-level=LOG_WARNING
      - --file-cache-timeout-in-seconds=3600