description: PhillyTools ConfigFile for s3prl

# AML 
target:
#  name: itpeastusv100cl
#  name: itpwus2v100cl
#  name: itplabrr1cl1
#  name: itpseasiav100cl
  name: itpscusv100cl
#  name: itpeusp100cl
#  name: itpeusp40cl
  service: amlk8s
  vc: resrchvc

# docker environment
environment:
  image: sanyuanchen/s3prl_v2:s3prl_v2

# code dir
code:
  local_dir: .

# job configuration
# amlt run .\scripts\itp\pretrained_models_asv.yaml pretrained_models_asv_mn_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep_1200kstep_1025k -y

jobs:
  - name: training
    sku: G8
#    sku: G1
    sku_count: 1
    command:
      - bash scripts/itp/bash/pretrained_models_asv.sh hubert_models mn_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep_1200kstep_1025k 512 1e-4 1 8
#      - sleep infinity

# azure blob configuration
storage:
  data_blob:
    container_name: models
    mount_dir: /datablob
    storage_account_name: tsstd01eus
#    storage_account_name: tsstd01scus
#    storage_account_name: tsstd01wus2
    mount_options:
      - -o
      - attr_timeout=240
      - -o
      - entry_timeout=240
      - -o
      - negative_timeout=120
      - -o
      - allow_other
      - --log-level=LOG_WARNING
      - --file-cache-timeout-in-seconds=3600