description: PhillyTools ConfigFile for s3prl

# AML 
target:
#  name: itpeastusv100cl
#  name: itpeusp100cl
  name: itpeusp40cl
  service: amlk8s
  vc: resrchvc

# docker environment
environment:
  image: sanyuanchen/s3prl_v2:s3prl_v2

# code dir
code:
  local_dir: .

# job configuration
  # amlt run .\scripts\itp\pretrained_models_er.yaml pretrained_models_er_mn_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep_1200kstep_1025k_b32_1e4_1_f1 -y

jobs:
  - name: training
    sku: G4
#    sku: G1
    sku_count: 1
    command:
      - bash scripts/itp/bash/pretrained_models_er.sh hubert_models mn_hubert_pretrain_base_iter3_94k_mnp0_mp02_grep_1200kstep_1025k 32 1e-4 1 4 1

# azure blob configuration
storage:
  data_blob:
    container_name: models
    mount_dir: /datablob
    storage_account_name: tsstd01eus
    mount_options:
      - -o
      - attr_timeout=240
      - -o
      - entry_timeout=240
      - -o
      - negative_timeout=120
      - -o
      - allow_other
      - --log-level=LOG_WARNING
      - --file-cache-timeout-in-seconds=3600